Исправляет ошибки
htmlacademy-htmlcss/1966385-sedona-36 pull request #3
Opened 2023-02-08 17:06 UTC by kol5ack

2023-02-13 09:19 UTC, vadimrahmanov requested changes

2023-02-13 09:19 UTC, vadimrahmanov commented on index.html
> +        <a href=" ">Гостиницы</a>
Там где, нету ссылки используй "#", но конкретно тут должна быть ссылка на Каталог.

2023-02-13 09:19 UTC, vadimrahmanov commented on index.html
> +        <p class="advantages-discription">Все достопримечательности находятся очень близко</p>
description пишется через "e"

2023-02-13 09:19 UTC, vadimrahmanov commented on index.html
> +      </div>
Это должно быть внутри списка в <li>, также как первая колонка с изображением.

2023-02-13 09:19 UTC, vadimrahmanov commented on index.html
>      <ul>
нету класса. Нужен для дальнейшей стилизации.

2023-02-13 09:19 UTC, vadimrahmanov commented on index.html
> +        <p class="service-discription">Не только китайскоого, но и настоящего местного производства</p>
Две буквы "o" в слове "китайского"

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +          <a href="#">Главная</a>
Тут должна быть ссылка на Главную

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
>      <a class="logo" href="index.html">
Убери здесь атрибут href, т.к мы уже на главной

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +          <a href="#">Гостиницы</a>
Здесь не нужен href, так как мы уже на этой странице.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +      <ul class="breadcrumbs">
Тут можно заменить на `<ol>`

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
>      <form action="catalog-checkbox">
класс неверный. Это форма, а не чекбокс. Также отсутствует атрибуты `method, action`

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +        <label class="filter-items">Бассейн</label>
label не связан с полем.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +        <label class="filter-items">Парковка</label>
label не связан с полем.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +          <label class="filter-items">Wi-Fi</label>
label не связан с полем.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +        <label class="filter-items">Гостиница</label>
label не связан с полем.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +        <label class="filter-items">Мотель</label>
label не связан с полем.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +        <label class="filter-items">Апортаменты</label>
label не связан с полем.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +  </ul>
у тебя форма не закрыта. Нету закрывающего тэга `</form>`

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +    <h1 class="hotel-results">Найдено гостиниц: 38</h1>
h1 заголовок высшего уровня, который используется 1 раз на странице для заголовка всей страницы. Тут его использование недопустимо.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +        <button class="hotell-card-follow" name="in-favorite">В Избранное</button>
Кнопке атрибут name не нужен.

2023-02-13 09:19 UTC, vadimrahmanov commented on catalog.html
> +    <ul class="pagitaion-list">
опечатка в слове

2023-02-14 15:36 UTC, vadimrahmanov requested changes

2023-02-14 15:36 UTC, vadimrahmanov commented on index.html
> +    <h2 class="iterest-question">Заинтересовались?</h2>
опечатка в слове Interest

2023-02-14 15:36 UTC, vadimrahmanov commented on index.html
>      <ul>
класс не добавил

2023-02-14 15:36 UTC, vadimrahmanov commented on catalog.html
> +    <button class="button" type="reset">Сбросить</button>
Внутри списков не могут находиться никакие элементы кроме `<li>`, а уже внутри них могут

2023-02-14 15:36 UTC, vadimrahmanov commented on catalog.html
> +    <form class="catalog-filters" method="get" action="">
атрибут action должен содержать адрес (echo.htmlacademy.ru)

2023-02-14 15:36 UTC, vadimrahmanov commented on catalog.html
> +        </li>
id должен быть уникальным на страницу. Нельзя делать одинаковый id. Он может быть лишь 1 на страницу.

2023-02-14 15:36 UTC, vadimrahmanov commented on catalog.html
>          <span class="hotel">Гостиница</span>
У тебя на 146 строчке просто закрытый див, у которого нету открытого. Просто удали

2023-02-14 15:36 UTC, vadimrahmanov commented on index.html
>    <nav class="navigation">
У тебя изображение на 12 строчке с логотипом содержит атрибут "href", которого не может быть в изображении. Также нельзя вставлять десятичные значения в атрибуты width, height

2023-02-14 15:36 UTC, vadimrahmanov commented on index.html
>        <div class="advantages-item">
В списке не может быть элемент div сразу, только внутри li.

2023-02-14 15:36 UTC, vadimrahmanov commented on index.html
>        <div class="advantages-item">
Тоже самое, что и выше.

2023-02-15 14:32 UTC, vadimrahmanov requested changes

2023-02-15 14:32 UTC, vadimrahmanov commented on index.html
> +        <a href="#">Главная</a></li>
Тут можно вообще убрать атрибут `href`, так как мы уже на главной.

2023-02-15 14:32 UTC, vadimrahmanov commented on index.html
> +        <label for="appointment-name">Ваш e-mail</label>
здесь нужно `for="email"`, так как ты снизу изменил ID

2023-02-15 14:32 UTC, vadimrahmanov commented on catalog.html
> +          <a href="#">Гостиницы</a>
Не исправлено. Тут атрибут `href` не нужен, мы и так на странице каталога

2023-02-15 14:32 UTC, vadimrahmanov commented on catalog.html
> +        <label for="appointment-name">Ваш e-mail</label>
Тут также как на главной неверное значение т.к ты изменил ID снизу.

2023-02-15 14:32 UTC, vadimrahmanov commented on catalog.html
>            <input class="catalog-housing-list" type="checkbox" id="infrastructure-items" name="apportaments">
У всех Inputов одинаковый ID.

2023-02-16 11:16 UTC, kol5ack reviewed
Исправляет замечания

2023-02-17 14:58 UTC, merged